if plot_scatter
    line([0, 1], [0, 1], 'color', 'k')
    text(0.05, 0.95, sprintf('p = %1.2g\nN = %i', ...
        signtest(qi_all{idx.gor}, qi_all{idx.mul}), ...
        length(qi_all{2})), ...
         'units', 'normalized', ...
         'horizontalalignment', 'left', ...
         'verticalalignment', 'top')   
    xlabel(sprintf('Quality Index\n%s', x_model))
    ylabel(sprintf('Quality Index\n%s', y_model))
    ylim([ymin, ymax])
else
    z = y - x;
    temp = histogram(z, linspace(xmin, xmax, num_bins), ...
        'edgecolor', 'none');
    ybounds = get(gca, 'ylim');
    line([0, 0], [0, ybounds(2)], 'color', 'k')
    line([median(z), median(z)], [0, ybounds(2)], ...
        'color', 'k', 'linestyle', ':')
    text(0.05, 0.95, sprintf('p = %1.2g\nN = %i', ...
        signtest(x, y), length(x)), ...
         'units', 'normalized', ...
         'horizontalalignment', 'left', ...
         'verticalalignment', 'top')
    xlabel(sprintf('QI: %s-\n%s', y_model, x_model))
    title(sprintf('\\DeltaQI = %3.2f', median(z)), ...
        'interpreter', 'tex')
end
xlim([xmin, xmax])
clean_plot